### ISSUE TITLE
"Occulus Rift" should be "Oculus Rift"

### ISSUE THREAD

**Issue by jackyliang** [drexelieee/dragonhacks#1]
Picture: http://puu.sh/lmKZ6/00fcd29382.jpg

Solution: Change to "Oculus Rift"

**Comment by siddhanathan** [comment]
It should be fixed by https://github.com/drexelieee/dragonhacks/commit/bb348357a4832386fd7de24c2d41af30f222273c. Also, @jackyliang you should have commit access.
